PlakDukkani-/PlakDukkani.UI.MVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PlakDukkani.UI.MVC.Helpers;
using PlakDukkani.BLL.Abstract;
using PlakDukkani.BLL.Concrete;
using PlakDukkani.BLL.Concrete.ResultServiceBLL;
using PlakDukkani.ViewModel.CartViewModels;
using PlakDukkani.ViewModel.Constraints;

namespace PlakDukkani.UI.MVC.Controllers
{
    public class CartController : Controller
    {
        IAlbumBLL albumService;
        public CartController(IAlbumBLL albumService)
        {
            this.albumService = albumService;
        }

        public IActionResult Index() //Sepet Sayfası 
        {
            Cart cart = HttpContext.Session.Get<Cart>("cart");
            if (cart == null)
            {
                ViewBag.Message = CartMessage.CartBosHatasi;
                return View();
            }
            return View(cart);
        }

        public IActionResult AddToCart(int id)
        {
            Cart cart = HttpContext.Session.Get<Cart>("cart");
            if (cart == null)
            {
                cart = new Cart();
            }

            ResultService<CartItem> result = albumService.GetCartById(id);
            if (!result.HasError)
            {
                CartItem item = result.Data;
                item.Quantity = 1;
                cart.Add(item);
                HttpContext.Session.Set<Cart>("cart", cart);
            }
            return PartialView("_cartButton", cart.TotalQuantity);
        }

        public IActionResult UpdateToCart(int id, short quantity)
        {
            Cart cart = HttpContext.Session.Get<Cart>("cart");
            cart.Update(id, quantity);
            HttpContext.Session.Set<Cart>("cart", cart);
            return PartialView("_cartTable", cart);
        }
        public IActionResult DeleteToCart(int id)
        {
            Cart cart = HttpContext.Session.Get<Cart>("cart");
            cart.Delete(id);
            HttpContext.Session.Set<Cart>("cart", cart);
            return PartialView("_cartTable", cart);
        }

    }
}

PlakDukkani-/PlakDukkani.UI.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PlakDukkani.BLL.Abstract;
using PlakDukkani.BLL.Concrete.ResultServiceBLL;
using PlakDukkani.ViewModel.AlbumViewModels;
using PlakDukkani.ViewModel.Constraints;
using System.Collections.Generic;

namespace PlakDukkani.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        //SOLID D => Dependency Inversion 
        //Dependency Injection Pattern 
        //Ctor Dep Injection 
        IAlbumBLL albumService;
        public HomeController(IAlbumBLL albumService)
        {
            this.albumService = albumService;
        }

        //IAlbumBLL albumservice = new AlbumService();
        public IActionResult Index()
        {
            ResultService<List<SingleAlbumVM>> albumResult = albumService.GetSingleAlbums();
            if (!albumResult.HasError)
            {
                return View(albumResult.Data);
            }
            else
            {
                ViewBag.Message = albumResult.Errors[0].ErrorMessage;
                return View();
            }
        }

        public IActionResult AlbumDetail(int id)
        {
            ResultService<AlbumDetailVM> result = albumService.GetAlbumById(id);
            if (result.HasError) 
            {
                ViewBag.Message = AlbumMessage.idHatasi;
                return View();
            }         
            return View(result.Data);
        }
        public IActionResult AlbumStore()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
    }
}

PlakDukkani-/PlakDukkani.UI.MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PlakDukkani.BLL.Abstract;
using PlakDukkani.BLL.Concrete.ResultServiceBLL;
using PlakDukkani.ViewModel.Constraints;
using PlakDukkani.ViewModel.UserViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlakDukkani.UI.MVC.Controllers
{
    //TODO: Session Araştır 
    //Sepet Viewı oluştur 
    public class UserController : Controller
    {
        IUserBLL userService;
        public UserController(IUserBLL userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(UserCreateVM user)
        {
            if (ModelState.IsValid)
            {
                ResultService<UserCreateVM> resultService = userService.Insert(user);
                return RedirectToAction(nameof(Login));
            }
            return View(user);
        }

        [HttpGet]
        public IActionResult ActivedUser(Guid id)
        {
            ResultService<bool> result = userService.ActivedUser(id);
            if (result.Data)
            {
                return RedirectToAction(nameof(Login), nameof(UserController));
            }
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (Request.Cookies["cookie"] != null)
            {
                string bilgi = Request.Cookies["cookie"];
                string[] bilgiParcasi = bilgi.Split("|");
                UserLoginVM userLogin = new UserLoginVM();
                userLogin.Email = bilgiParcasi[0];
                userLogin.Password = bilgiParcasi[1];
                userLogin.IsRemember = true;
                return View(userLogin);
            }
            return View();
        }

        [HttpPost]
        public IActionResult Login(UserLoginVM user)
        {
            if (user.IsRemember)
            {
                CookieOptions cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddDays(10);

                Response.Cookies.Append("cookie", user.Email + "|" + user.Password, cookieOptions);
            }
            else
            {
                //Cookie nasıl silinir.
            }
            if (ModelState.IsValid)
            {
                ResultService<bool> result = userService.CheckUserForLogin(user.Email, user.Password);
                if (result.HasError)
                {
                    ViewBag.Message = UserMessage.LoginMessage;
                }
                else
                {
                    return RedirectToAction(nameof(Index), "Home");
                }
            }
            return View();

        }
    }
}

PlakDukkani-/PlakDukkani.UI.MVC/Views/Cart/Index.cshtml
@model Cart

@{
    ViewData["Title"] = "CartIndex";
}


<section class="featured-artist-area section-padding-100 bg-img bg-overlay bg-fixed" style="background-image: url(img/bg-img/bg-4.jpg); height:100vh;">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-12 m-5">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Discount</th>
                            <th>SubTotal</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="tableData">
                        <partial name="_cartTable" model="@Model" />
                    </tbody>                 
                </table>
            </div>
        </div>
    </div>
</section>



@section scripts {
    <script>
        function CartUpdate(cartId, value) {
            $.ajax({
                type: "GET",
                url: "/Cart/UpdateToCart",
                data: {
                    id: cartId,
                    quantity: value
                }
            })
                .done(function (cartTablePartial) {
                    console.log("istek basarılı");
                    console.log(cartTablePartial);
                    $("#tableData").html(cartTablePartial);
                    let totalQuantity = $("#Totalquantity").val();
                    $(".quantity").text(totalQuantity)
                });
        }

        function CartDelete(cartId) {
            var cvp = confirm("Albumu silmek istiyor musunuz ?")
            if (cvp) {
                $.ajax({
                    type: "GET",
                    url: "/Cart/DeleteToCart",
                    data: { id: cartId },
                    success: function (data) {
                        $("#tableData").html(data);
                        let totalQuantity = $("#Totalquantity").val();
                        $(".quantity").text(totalQuantity)
                    }
                });
            }
        }

    </script>
}

PlakDukkani-/PlakDukkani.UI.MVC/Views/Home/AlbumDetail.cshtml
@model AlbumDetailVM

@{
    ViewData["Title"] = "AlbumDetail";  
}

<!-- ##### Featured Artist Area Start ##### -->
<section class="featured-artist-area section-padding-100 bg-img bg-overlay bg-fixed" style="background-image: url(../../img/bg-img/bg-4.jpg);">
    <div class="container">
        <div class="row align-items-start">
            <div class="col-12 col-md-5 col-lg-4">
                <div class="featured-artist-thumb">
                    <img src="~/@Model.AlbumArtUrl" alt="">
                </div>
            </div>
            <div class="col-12 col-md-7 col-lg-8">
                <div class="featured-artist-content">
                    <!-- Section Heading -->
                    <div class="section-heading white text-left mb-30">
                        <h1>@Model.Title</h1>
                        <h2>@Model.Price ₺</h2>
                    </div>
                    <p>@Model.ArtistFullName</p>
                    <p>@Model.GenreName</p>

                    <p>@Model.ArtistFullName</p>
                    <div class="oneMusic-buttons-area mb-100">
                        <a id="sepeteEkle" data-id="@Model.ID" class="btn oneMusic-btn m-2">Sepete Ekle<i class="fa fa-cart-plus"></i></a>
                        @*<a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@Model.ID" class="btn oneMusic-btn m-2">Sepete Ekle<i class="fa fa-cart-plus"></i></a>*@

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Featured Artist Area End ##### -->

@section scripts
{
    <script>
        @*let id = @ViewContext.RouteData.Values["id"];*@

        let buton = document.querySelector("#sepeteEkle");
        let id = buton.getAttribute("data-id");
        buton.addEventListener("click",AddCart)

        
        function AddCart() {
            $.ajax({
                type: "GET",
                url: "/Cart/AddToCart/" + id,
                //contentType: "application/json; charset=utf-8",
                //data:               
            })
                .done(function (cartButtonPartial) {
                    //istekten geri dönene yapılacak iş
                    console.log("aaaa")
                    $(".cart-btn").html(cartButtonPartial);
                    $.magnificPopup.close()
                })
                .fail(function () {
                    console.error("işlem başarısız")
                });
        }
    </script>
}

PlakDukkani-/PlakDukkani.UI.MVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url(../../img/bg-img/breadcumb.jpg);">
    <div class="bradcumbContent">
        <p>See what’s new</p>
        <h2>Contact</h2>
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Contact Area Start ##### -->
<section class="contact-area section-padding-100-0">
    <div class="container">
        <div class="row">

            <div class="col-12 col-lg-3">
                <div class="contact-content mb-100">
                    <!-- Title -->
                    <div class="contact-title mb-50">
                        <h5>Contact Info</h5>
                    </div>

                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-placeholder"></span>
                        </div>
                        <p>1481 Creekside Lane Avila Beach, CA 931</p>
                    </div>

                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-smartphone"></span>
                        </div>
                        <p>+53 345 7953 32453</p>
                    </div>

                    <!-- Single Contact Info -->
                    <div class="single-contact-info d-flex align-items-center">
                        <div class="icon mr-30">
                            <span class="icon-mail"></span>
                        </div>
                        <p>yourmail@gmail.com</p>
                    </div>

                    <!-- Contact Social Info -->
                    <div class="contact-social-info mt-50">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Behance"><i class="fa fa-behance" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                    </div>

                </div>
            </div>

            <div class="col-12 col-lg-9">
                <!-- ##### Google Maps ##### -->
                <div class="map-area mb-100">                

                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2644.6500849147537!2d29.02359879311888!3d40.988105175170425!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab8677b5e0043%3A0xbfd8727d240c096!2zQ2FmZXJhxJ9hLCBNw7xow7xyZGFyIENkLiBObzo3NiwgMzQ3MTAgS2FkxLFrw7Z5L8Swc3RhbmJ1bA!5e0!3m2!1str!2str!4v1646054317717!5m2!1str!2str" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- ##### Contact Area End ##### -->

PlakDukkani-/PlakDukkani.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>@ViewData["Title"]</title>

    <!-- Favicon -->
    <link rel="icon" href="~/img/core-img/favicon.ico">

    <!-- Stylesheet -->

    <link rel="stylesheet" href="~/style.css">

</head>
<body>

    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="oneMusic-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="oneMusicNav">

                        <!-- Nav brand -->
                        <a asp-action="Index" asp-controller="Home" class="nav-brand"><img src="~/img/core-img/logo.png" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                                    <li><a asp-action="AlbumStore" asp-controller="Home">Albums</a></li>
                                    <li>
                                        <a href="#">Pages</a>
                                        <ul class="dropdown">
                                            <li><a href="index.html">Home</a></li>
                                            <li><a href="albums-store.html">Albums</a></li>
                                            <li><a href="event.html">Events</a></li>
                                            <li><a href="blog.html">News</a></li>
                                            <li><a href="contact.html">Contact</a></li>
                                            <li><a href="elements.html">Elements</a></li>
                                            <li><a href="login.html">Login</a></li>
                                            <li>
                                                <a href="#">Dropdown</a>
                                                <ul class="dropdown">
                                                    <li><a href="#">Even Dropdown</a></li>
                                                    <li><a href="#">Even Dropdown</a></li>
                                                    <li><a href="#">Even Dropdown</a></li>
                                                    <li>
                                                        <a href="#">Even Dropdown</a>
                                                        <ul class="dropdown">
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Even Dropdown</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                    <li><a href="event.html">Events</a></li>
                                    <li><a href="blog.html">News</a></li>
                                    <li><a href="contact.html">Contact</a></li>
                                </ul>

                                <!-- Login/Register & Cart Button -->
                                <div class="login-register-cart-button d-flex align-items-center">
                                    <!-- Login/Register -->
                                    <div class="login-register-btn mr-50">
                                        <a asp-action="Login" asp-controller="User" id="loginBtn">Login</a>/
                                        <a asp-action="Register" asp-controller="User" id="loginBtn">Register</a>
                                    </div>

                                    <!-- Cart Button -->                                 
                                        <div class="cart-btn">
                                            @{
                                                    @using Microsoft.AspNetCore.Http;
                                                    @using PlakDukkani.UI.MVC.Helpers;
                                                    Cart cart = new Cart();
                                                    if (Context.Session.Get<Cart>("cart") != null)
                                                    {
                                                        cart = Context.Session.Get<Cart>("cart");
                                                    }

                                                }
                                                <partial name="_cartButton" model="@cart.TotalQuantity" />
                                        </div>

                        
                                </div>
                            </div>
                            <!-- Nav End -->

                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    @RenderBody()

    @if (ViewData["Title"].ToString() == "Contact")
    {
        @*@await Html.PartialAsync("_contactAreaBlack", false)*@
        <partial name="_contactAreaWhite" />
    }
    else if (ViewData["Title"].ToString() != "Register" && ViewData["Title"].ToString() != "CartIndex")
    {
        <partial name="_contactAreaBlack" />
    }

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <div class="container">
            <div class="row d-flex flex-wrap align-items-center">
                <div class="col-12 col-md-6">
                    <a href="#"><img src="~/img/core-img/logo.png" alt=""></a>
                    <p class="copywrite-text">
                        <a href="#">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

                <div class="col-12 col-md-6">
                    <div class="footer-nav">
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Albums</a></li>
                            <li><a href="#">Events</a></li>
                            <li><a href="#">News</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->

    <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/js/bootstrap/bootstrap.min.js"></script>
    <!-- All Plugins js -->
    <script src="~/js/plugins/plugins.js"></script>
    <!-- Active js -->
    <script src="~/js/active.js"></script>

    @RenderSection("scripts", false)
    @*<script>
        $.ajax({
            url: "Cart/GetCartButton",
            type: "GET"
        }).done(function (cartButtonPartial) {
            $(".cart-btn").html(cartButtonPartial);
        });
    </script>*@

   
</body>
</html>

PlakDukkani-/PlakDukkani.UI.MVC/Views/Shared/_SingleAlbumArea.cshtml
@model List<SingleAlbumVM>

<div class="row">

    @foreach (SingleAlbumVM item in Model)
    {
        <!-- Single Album Area -->
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <div class="single-album-area wow fadeInUp" data-wow-delay="100ms">
                <div class="album-thumb">
                    <img src="~/@item.AlbumArtUrl" alt="">       


                    <!-- Album Price -->
                    <div class="album-price">
                        <p>@item.Price ₺</p>
                    </div>
                    <!-- Play Icon -->
                    <div class="play-icon">
                        <a asp-action="AlbumDetail" asp-controller="Home" asp-route-id="@item.ID"  class="video--play--btn"><span class="icon-zoom-in"></span></a>
                    </div>
                </div>
                <div class="album-info">
                    <a href="#">
                        <h5>@item.Title</h5>
                    </a>
                    <p>@item.FullName</p>
                </div>
            </div>
        </div>
    }
</div>

PlakDukkani-/PlakDukkani.UI.MVC/Views/Shared/_cartButton.cshtml
<!-- Cart Button -->
@model int 
    <p>
        <span class="icon-shopping-cart"></span>
        <a asp-action="Index" asp-controller="Cart">
            <span class="quantity">@Model</span>
        </a>
    </p>

PlakDukkani-/PlakDukkani.UI.MVC/Views/User/Login.cshtml
@model UserLoginVM

@{
    ViewData["Title"] = "Login";
}

<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url(../../img/bg-img/breadcumb3.jpg);">
    <div class="bradcumbContent">
        <p>See what’s new</p>
        @if (ViewBag.Message != null)
        {
            <h3>@ViewBag.Message</h3>
        }
        else
        {
            <h3>Login</h3>
        }
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Login Area Start ##### -->
<section class="login-area section-padding-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <div class="login-content">
                    <h3>Welcome Back</h3>
                    <!-- Login Form -->
                    <div class="login-form">
                        <form asp-action="Login" asp-controller="User" method="post">
                            <div class="form-group">

                                <label asp-for="Email"></label>
                                <input asp-for="Email" class="form-control">
                                <span asp-validation-for="Email" class="form-text text-muted"></span>
                            </div>

                            <div class="form-group">

                                <label asp-for="Password"></label>
                                <input asp-for="Password" type="text" class="form-control">
                                <span asp-validation-for="Password" class="form-text text-muted"></span>
                            </div>

                            <div class="form-group form-check">
                                <input asp-for="IsRemember" type="checkbox" class="form-check-input">
                                <label asp-for="IsRemember">Beni Hatırla</label>
                            </div>

                            <button type="submit" class="btn oneMusic-btn mt-30">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Login Area End ##### -->

PlakDukkani-/PlakDukkani.UI.MVC/Views/User/Register.cshtml
@model UserCreateVM

@{
    ViewData["Title"] = "Register";
}

<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img bg-overlay" style="background-image: url(../../img/bg-img/breadcumb3.jpg);">
    <div class="bradcumbContent">
        <p>See what’s new</p>
        <h2>Login</h2>
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### Login Area Start ##### -->
<section class="login-area section-padding-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <div class="login-content">
                    <h3>Welcome</h3>
                    <!-- Login Form -->
                    <div class="login-form">

                        <form asp-action="Register" asp-controller="User" method="post">

                            <div class="form-group">
                                <label asp-for="FirstName"></label>
                                <input asp-for="FirstName" class="form-control">
                                <span asp-validation-for="FirstName" class="form-text text-muted"></span>
                            </div>
                            <div class="form-group">

                                <label asp-for="LastName"></label>
                                <input asp-for="LastName" class="form-control">
                                <span asp-validation-for="LastName" class="form-text text-muted"></span>
                            </div>

                            <div class="form-group">

                                <label asp-for="Email"></label>
                                <input asp-for="Email" class="form-control">
                                <span asp-validation-for="Email" class="form-text text-muted"></span>
                            </div>

                            <div class="form-group">

                                <label asp-for="Password"></label>
                                <input asp-for="Password" class="form-control">
                                <span asp-validation-for="Password" class="form-text text-muted"></span>
                            </div>

                            <div class="form-group">

                                <label asp-for="PhoneNumber">Phone Number</label>
                                <input asp-for="PhoneNumber" class="form-control">
                                <span asp-validation-for="PhoneNumber" class="form-text text-muted"></span>
                            </div>

                            <div class="form-group">

                                <label asp-for="Address"></label>
                                <input asp-for="Address" class="form-control">
                                <span asp-validation-for="Address" class="form-text text-muted"></span>
                            </div>

                            <button type="submit" class="btn oneMusic-btn mt-30">Register</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ##### Login Area End ##### -->